---
- name: Common setup on all VMs
  hosts: all
  become: true
  roles:
    - common

- name: Configure database VM
  hosts: db
  become: true
  roles:
    - db

- name: Configure worker VM
  hosts: workers
  become: true
  roles:
    - worker
