---
- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart mywebapp
  ansible.builtin.systemd:
    name: mywebapp
    state: restarted

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
