qemu-system-aarch64 \
    -M virt,highmem=on \
    -cpu max \
    -accel hvf \
    -smp 2 \
    -m 2048 \
    -bios /opt/homebrew/share/qemu/edk2-aarch64-code.fd \
    -drive file=runner.qcow2,if=virtio,format=qcow2 \
    -drive file=ubuntu-26.04-live-server-arm64.iso,id=cdrom,if=none,format=raw,readonly=on \
    -device virtio-scsi-device \
    -device scsi-cd,drive=cdrom \
    -netdev user,id=net0,hostfwd=tcp::8080-:80,hostfwd=tcp::2222-:22 \
    -device virtio-net-device,netdev=net0 \
    -serial stdio \
    -display none